# Generated by Django 4.1.7 on 2023-04-20 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 4, 20, 11, 59, 39, 348542, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
